### ISSUE TITLE
搜索框移动端样式偏移

### ISSUE THREAD

**Issue by SwordMasterJS** [kevinng77/halo-theme-knarc#1]
![2VJX@28H}_GR} KO7LPXX7](https://user-images.githubusercontent.com/32394118/170820443-f8f0facf-828b-48aa-bf0d-4694f9954bf7.jpg)

一个小问题，很喜欢这个主题，希望作者能越做越好

**Comment by kevinng77** [comment]
你好哈，谢谢支持和反馈~仓库已经更换了一种移动端搜索栏的展示方式，可以更新下主题试试看效果哈。

**Comment by SwordMasterJS** [comment]
感谢更新，反馈一下

电脑端，搜索框和搜索按钮距离过大，是否影响美观？
![7K2U7G5KQ{(AJ4RNXE`{U70](https://user-images.githubusercontent.com/32394118/170856827-7bf798d5-f795-4bc0-bb34-655ce21e31c1.png)

移动端，按钮出现椭圆形变
![4C1CB57C0E78C67AA5B852796B94D0DF](https://user-images.githubusercontent.com/32394118/170856851-b19492ae-14cd-4992-a046-049997c4d348.jpg)

移动端搜索是无效的

**Comment by kevinng77** [comment]
+ em 电脑端的搜索按钮和搜索栏我之前显示是正常的，尝试重新安装下主题试试？
+ 搜索图标换成正圆了哈，之前太懒直接用padding的方式随便画了个圆。
